language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

before_install:
    - |
        if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew update                                                         # this swaps python versions and makes 3 the default one

            if [ "$WANTED_PYTHON_VERSION" == "2.7" ]; then
                brew reinstall python\@2 || brew link --overwrite python\@2     # install and link python2 and pip2 to /usr/local/bin
                export PATH=/usr/local/opt/python\@2/bin:$PATH
                export PYTHON_EXE=python
                export PIP_EXE=pip
            else
                brew reinstall python                                           # install and link python3 and pip3 to /usr/local/bin
                export PATH=/usr/local/opt/python/bin:$PATH
                export PYTHON_EXE=python3
                export PIP_EXE=pip3
            fi

            export CK_PLATFORM_NAME="generic-macos "                            # used later by CK
        else
            sudo apt-get install python-pip
            export WANTED_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION                 # since Python is supported in Linux, get it from Travis
            export CK_PLATFORM_NAME="generic-linux "                            # used later by CK (note the trailing space to make the choice unique)
            export PYTHON_EXE=python
            export PIP_EXE=pip
        fi

install: 
    - "$PIP_EXE install coveralls"
    - "$PIP_EXE install pyyaml"

script: 
    - "$PYTHON_EXE setup.py install"
    - "ck pull repo:ck-web"
    - "coverage run -m tests.test"

after_success: coveralls
