---
  resnet50:
    Offline:
      target_qps: 1
    Server:
      target_qps: 1.0
    SingleStream:
      target_latency: 100
    MultiStream:
      target_latency: 400
  retinanet:
    Offline:
      target_qps: 1.0
    Server:
      target_qps: 1.0
    SingleStream:
      target_latency: 1000
    MultiStream:
      target_latency: 4000
  bert-99:
    Offline:
      target_qps: 1.0
    Server:
      target_qps: 1.0
    SingleStream:
      target_latency: 1000
    MultiStream:
      target_latency: 8000
  bert-99.9:
    Offline:
      target_qps: 1.0
    Server:
      target_qps: 1.0
    SingleStream:
      target_latency: 1000
    MultiStream:
      target_latency: 8000
